//***************************************************
// 
// Teensy Synth DIY Workshop v. Nov 2022
//
// This is a template file which contains some useful
// "preparatory" code 
// 
//
// Connection to Teensy:
//
//  Pin G  --> ground bus
//  Pin 3v --> 3v bus
//
//  Pin 5v --> dac board Vcc
//  Pin 20 --> dac board LCK
//  Pin 21 --> dac board BCK
//  Pin 7  --> dac board DIN
//
//  Pin 14 --> Potentiometer OSC GAIN 
//  Pin 15 --> Potentiometer OSC FREQ
//  Pin 16 --> Potentiometer FILTER CUTOFF
//  Pin 17 --> Potentiometer LFO RATE
//  Pin 18 --> Potentiometer SEQUENCER SPEED
//  Pin 19 --> Potentiometer SEQUENCER OCTAVES RANGE
//   [all connections to pots central pin]
//
//  Pin 1 --> Button 1 FM on/off
//  Pin 2 --> Button 2 Cutoff Modulation on/off
//  Pin 3 --> Button 3 Sequencer on/off
//  [the other pin of each button --> Ground]
//
//  Pin 5 --> resistor --> LED+
//  Led- --> Ground
//
//  dac board SCK --> Ground bus
//  dac board XMT --> 3v bus
//  dac board GND,FMT,SCL,DMP,FLT --> Ground bus
//
//***************************************************

// useful headers - do not remove
// make shure this file is in the same folder 
#include "DIYSynthWorkshop.h"  

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Paste here the code generated by the AudioDesign Tool
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Setup: The stuff in here is executed only once at startup
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
void setup() {

   // Setup input knobs to control the synth parameters
  setupKnobs();
  
  // Setup serial communication with your laptop to print debug info
  Serial.begin(9600);

   // Allocate memory for the audio processing - do not remove this line!
  // note: you may need to increase this value later on
  AudioMemory(50);

  // **** Your setup code here ****


  // **** End of setup code  ****

}


//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Loop: The stuff in here is executed continuously
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
void loop() {

  // do not remove this line
  updateKnobs();


  // **** Your loop code here ****
  
  

  
  // **** End of your loop code ****


  // a small delay in the loop
  delay(5);  
}
