//***************************************************
// 
// Teensy Synth DIY Workshop v. Nov 2024
//
// This is a template file which contains some useful
// "preparatory" code 
// 
//
// Connection to Teensy:
//
//  Pin G  --> ground bus
//  Pin 3v --> 3v bus
//
//  Pin 5v --> dac board Vcc
//  Pin 20 --> dac board LCK
//  Pin 21 --> dac board BCK
//  Pin 7  --> dac board DIN
//
//  Pin 14 --> Potentiometer OSC GAIN 
//  Pin 15 --> Potentiometer OSC FREQ
//  Pin 16 --> Potentiometer FILTER CUTOFF
//  Pin 17 --> Potentiometer LFO RATE
//  Pin 18 --> Potentiometer SEQUENCER SPEED
//  Pin 19 --> Potentiometer SEQUENCER OCTAVES RANGE
//   [all connections to pots central pin]
//
//  Pin 1 --> Button 1 FM on/off
//  Pin 2 --> Button 2 Cutoff Modulation on/off
//  Pin 3 --> Button 3 Sequencer on/off
//  [the other pin of each button --> Ground]
//
//  Pin 5 --> resistor --> LED+
//  Led- --> Ground
//
//  dac board SCK --> Ground bus
//  dac board XMT --> 3v bus
//  dac board GND,FMT,SCL,DMP,FLT --> Ground bus
//
//  To run this code you also need to install 
//  the Smoothed library
//***************************************************

// useful headers - do not remove
// make shure this file is in the same folder 
#include "DIYSynthWorkshop.h"  

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Paste here the code generated by the AudioDesign Tool
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#include <Audio.h>
#include <Wire.h>
#include <SPI.h>
#include <SD.h>
#include <SerialFlash.h>

// GUItool: begin automatically generated code
AudioSynthWaveformModulated osc;   //xy=378.0000305175781,351.0000400543213
AudioOutputI2S           i2s1;           //xy=618.5714111328125,338.1428527832031
AudioConnection          patchCord1(osc, 0, i2s1, 0);
AudioConnection          patchCord2(osc, 0, i2s1, 1);
// GUItool: end automatically generated code


//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Setup: The stuff in here is executed only once at startup
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
void setup() {

   // Setup input knobs to control the synth parameters
  setupKnobs();
  
   // Allocate memory for the audio processing - do not remove this line!
  // note: you may need to increase this value later on
  AudioMemory(50);

  //**** Your setup code below this line ****

  osc.begin( 0.2, 300, WAVEFORM_TRIANGLE );


  //******** End of setup code  *************
}


//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Loop: The stuff in here is executed continuously
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
void loop() {

  // do not remove this line
  updateKnobs();


  //**** Add your loop code below this line ****
  
  // random sequencer
  // generate a random frequency
  //int freq = random(400,440);
  // set the frequency of the oscillator
  //osc.frequency(freq);
  //delay(100);


  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  // set the osc amplitude
  float value14 = readKnob(14);
  float amp = map(value14, 0.0, 1023.0, 0.0, 1.0 );
  osc.amplitude(amp);
  //Serial.println(value14);
  //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  // set the osc frequency
  float value15 = map( readKnob(15), 0.0, 1023.0, 0.0, 1.0 );
  
  float freq = 30.0 + powf(value15, 4.0) * 3000;

  osc.frequency( freq );

  Serial.println(value15);




  //********* End of your loop code ************


  // a small delay in the loop
  delay(5);  
}
